name: pathing_tool
description: "FRC All-In-One Autonomous/Pathing Tool"
publish_to: 'none'
version: 1.2.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  archive: ^3.6.1
  audio_video_progress_bar: ^2.0.3
  dartssh2: ^2.8.2
  file_picker: ^8.0.5
  fl_chart: ^0.68.0
  flutter:
    sdk: flutter
  flutter_colorpicker: ^1.0.3
  flutter_flow_chart: ^3.1.1
  flutter_iconpicker: ^3.3.3
  flutter_image_converter: ^0.3.3
  image: ^4.2.0
  matrices: ^1.2.7
  path_provider: ^2.1.3
  provider: ^6.0.4
  shared_preferences: ^2.2.3
  simple_snowfall: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-VariableFont_wdth,wght.ttf
  assets:
    - Images/game_field.png
    - Images/PolarBearHead.png
    - pubspec.yaml